name: Build Extensions

on:
  push:
    branches: [ main,"feature/autopublish" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build extensions
        run: |
          chmod +x buildScript.sh
          ./buildScript.sh

      - name: Zip Chrome
        run: |
          cd dist/chrome
          zip -r ../../chrome.zip .

      - name: Zip Firefox
        run: |
          cd dist/firefox
          zip -r ../../firefox.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-builds
          path: "*.zip"
          
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to Chrome Web Store
        id: publish-chrome-extension
        uses: puzzlers-labs/chrome-webstore-publish@v1
        with:
          mode: publish # Or `sign` to sign the extension and publish at a later step (manually).
          extension_id: ${{ vars.CHROME_EXTENSION_ID }}
          zip_file_path: ./dist/chrome.zip
          client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh_token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          publish_target: public # Or `testers` for internal publishing target to TrustedTesters.
          expedited_review: true # This does not guarantee an expedited Review process. But it makes an attempt.
          # Only one of the following should be provided:
          # crx_private_key: ${{ secrets.CRX_PRIVATE_KEY }}
          # crx_private_key_path: ./path/to/key.pem
